const CLUBS = "CLUBS";
const DIAMONDS = "DIAMONDS";
const HEARTS = "HEARTS";
const SPADES = "SPADES";

// events
const ADD_PLAYER = "ADD_PLAYER";
const REMOVE_PLAYER = "REMOVE_PLAYER";

const SET_SMALL_BLIND = "SET_SMALL_BLIND";
const REMOVE_SMALL_BLIND = "REMOVE_SMALL_BLIND";
const SET_BIG_BLIND = "SET_BIG_BLIND";
const REMOVE_BIG_BLIND = "REMOVE_BIG_BLIND";
const SET_DEALER = "SET_DEALER";
const REMOVE_DEALER = "REMOVE_DEALER";

const HAND_OUT_CARDS = "HAND_OUT_CARDS";
const FLOP = "FLOP";
const TURN = "TURN";
const RIVER = "RIVER";

const CALL = "CALL";
const BET = "BET";
const FOLD = "FOLD";

module.exports = {
    CLUBS, DIAMONDS, HEARTS, SPADES, ADD_PLAYER, REMOVE_PLAYER, SET_SMALL_BLIND, REMOVE_SMALL_BLIND,
    SET_BIG_BLIND, REMOVE_BIG_BLIND, SET_DEALER, REMOVE_DEALER, HAND_OUT_CARDS, FLOP, TURN, RIVER,
    CALL, BET, FOLD
}